-- Gerao de Modelo fsico
-- Sql ANSI 2003 - brModelo.



/*CREATE TABLE JOGADOR (
JDSENHA VARCHAR(30),
JDEMAIL VARCHAR(30),
JDNOME VARCHAR(30),
JDID INTEGER PRIMARY KEY,
JDLOGIN VARCHAR(30),
JDDATANASC VARCHAR(30)
);*/
/*
CREATE TABLE CENARIO (
CNID INTEGER PRIMARY KEY,
CNNOME VARCHAR(30),
CNIDMODELO INTEGER,
CNIDTEXTURA INTEGER
);

CREATE TABLE PERSONAGEM (
PGID INTEGER PRIMARY KEY,
PGNOME VARCHAR(30),
PGTEMPORESPAW INTEGER,
PGNIVEL INTEGER,
PGDINHEIRO INTEGER,
PGEXPERIENCIA INTEGER,
PGRACA INTEGER,
PGFORCA INTEGER,
PGAGILIDADE INTEGER,
PGDESTREZA INTEGER,
PGRESISTENCIA INTEGER,
PGINSTINTO INTEGER,
PGPONTOSVIDA INTEGER,
PGPONTOSPODER INTEGER,
PGATAQUESDISTANCIA INTEGER,
PGATAQUESCORPO INTEGER,
PGDANOCORPO INTEGER,
PGDANODISTANCIA INTEGER,
PGDEFESA INTEGER,
PGTAXAATAQUE INTEGER,
PGTEMPOCARGA INTEGER,
PGTIPOPERSONAGEM INTEGER,
PGLEALARANHA INTEGER,
PGLEALBESOURO INTEGER,
PGLEALESCORPIAO INTEGER,
PGLEALLOUVA INTEGER,
PGLEALVESPA INTEGER,
PGIDARMOR INTEGER,
PGIDWEAPON INTEGER,
PGX INTEGER,
PGZ INTEGER,
PGY INTEGER,
PGIDTEXTURA INTEGER,
PGIDMODELO INTEGER
);

CREATE TABLE PODER (
PDID INTEGER PRIMARY KEY,
PDNIVEL INTEGER,
PDDESCRICAO VARCHAR(200),
PDCUSTOPP INTEGER,
PDCUSTOTC INTEGER,
PDDANO INTEGER,
PDTIPOBUFF INTEGER
);

CREATE TABLE ITEMBASE (
ITID INTEGER PRIMARY KEY,
ITNIVELMAGICO INTEGER,
ITDURABILIDADE INTEGER,
ITNOME VARCHAR(30),
ITDESCRICAO VARCHAR(200),
ITALCANCE INTEGER,
ITVELOCIDADE INTEGER,
ITDROPAVEL BOOLEAN,
ITRACA INTEGER,
ITDANOMAX INTEGER,
ITDANOMIN INTEGER,
ITMODIFICADOR INTEGER,
ITVALOR INTEGER,
ITDEFESA INTEGER,
ITISTEMP BOOLEAN,
ITDURACAO INTEGER,
ITTIPO INTEGER,
ITLEALARANHA INTEGER,
ITLEALESCORPIAO INTEGER,
ITLEALLOUVA INTEGER,
ITLEALVESPA INTEGER,
ITLEALBESOURO INTEGER,
ITIDMODELO INTEGER,
ITIDTEXTURA INTEGER
);

CREATE TABLE PORTAL (
PTID INTEGER PRIMARY KEY,
PTLOCZ INTEGER,
PTDESTX INTEGER,
PTLOCX INTEGER,
PTDESTY INTEGER,
PTLOCY INTEGER,
PTDESTZ INTEGER,
PTIDCENARIODEST INTEGER
);

CREATE TABLE ITEM_RELACIONAL (
IRVALBONUS1 INTEGER,
IRPRECO INTEGER,
IRVALBONUS7 INTEGER,
IRVALBONUS6 INTEGER,
IRVALBONUS5 INTEGER,
IRVALBONUS4 INTEGER,
IRVALBONUS3 INTEGER,
IRVALBONUS2 INTEGER,
IRX INTEGER,
IRY INTEGER,
IRZ INTEGER,
ITID INTEGER,
PGID INTEGER,
CNID INTEGER,
FOREIGN KEY(ITID) REFERENCES ITEMBASE (ITID),
FOREIGN KEY(PGID) REFERENCES PERSONAGEM (PGID),
FOREIGN KEY(CNID) REFERENCES CENARIO (CNID)
);

CREATE TABLE JOGADOR_PERSONAGEM (
PGID INTEGER,
JDID INTEGER,
FOREIGN KEY(JDID) REFERENCES JOGADOR (JDID),
FOREIGN KEY(PGID) REFERENCES PERSONAGEM (PGID)
);
*/
CREATE TABLE PORTAL_CENARIO (
PTID INTEGER,
CNID INTEGER,
FOREIGN KEY(PTID) REFERENCES PORTAL (PTID),
FOREIGN KEY(CNID) REFERENCES CENARIO (CNID)
);

CREATE TABLE PODER_PERSONAGEM (
PGID INTEGER,
PDID INTEGER,
FOREIGN KEY(PGID) REFERENCES PERSONAGEM (PGID),
FOREIGN KEY(PDID) REFERENCES PODER (PDID)
);

CREATE TABLE PERSONAGEM_CENARIO (
CNID INTEGER,
PGID INTEGER,
FOREIGN KEY(CNID) REFERENCES CENARIO (CNID),
FOREIGN KEY(PGID) REFERENCES PERSONAGEM (PGID)
);