#pragma once

#include <string>

//-----------------------------------------------------------------------------------------
// CONSTANTES
//-----------------------------------------------------------------------------------------

const std::string SERVERHOST = "189.61.169.212";//"10.16.11.31"; // IP do servidor
const int SERVERPORT = 30003;          // Porta do servidor

const int PACKAGESIZE = 1400; // Tamanho do pacote de mensagens

//-----------------------------------------------------------------------------------------
// MENSAGENS
//-----------------------------------------------------------------------------------------

/*Identificador de Mensagens*/
/*enum TYPE_MESSAGE 
{
DISCONNECT = 0,
PING,
END_FRAME,
//MENSAGENS RECEBIDAS
LOGIN_OK = 33, // se o login foi OK
LOGIN_FAIL, //se o login falhou por algum motivo
SHOW_PERSONAGENS, //QTD PERSONAGENS QUE O JOGADOR POSSUI, E OS PERSONAGENS
CREATE_PLAYER_OK, //o player foi criado com sucesso
CREATE_PLAYER_FAIL, //não foi possível criar o player
DELETE_PLAYER_OK,	
DELETE_PLAYER_FAIL,
ENTER_CENARIO,//id cenario, POSICAO X, POSICAO Z, qtd Inimigos, qtdNPC, qtdVendedores, qtdPersonagensJogadores, qtdBolsa
ADD_PERSONAGEM, //atributos do outros persoangens NPC, Jogadores
ADD_BOLSA,//id bolsa, POSICAO X, POSICAO Z, estado bolsa
UPDATE_POSITION, //ID PERSONAGEM, POSICAO X, POSICAO Z
UPDATE_ESTADO, //IDPERSONAGEM, ESTADO
UPDATE_ATACK, //ID PERSONAGEM, ID ALVO, ID ATAQUE
OPENED_BOLSA, //ID BOLSA, ITENS DA BOLSA -1 se não houver nada
CLOSED_BOLSA, //ID BOLSA
UPDATE_EQUIP, //ID PERSONAGEM, ID ARMA, ID ARMADURA
SHOW_DAMAGE, //ID PERSONAGEM , DANO
CHAT, // MENSAGEM
REMOVE_ITEM,  //ID ITEM, QTD DINHEIRO
ADD_ITEM, //id do item, qtd dinheiro
PRICE_ITEM, //ID ITEM, PRECO
CHANGE_BUFFS, //ID BUFF, ESTADO
CHANGE_MONEY, //quantidade
CHANGE_BONUS, //HABILIDADES PRIMARIAS E SECUNDARIAS DO JOGADOR EM ORDEM ALFABETICA
UPDATE_PVPPNIVEL,  //ID PERSONAGEM, PONTOS VIDA, PONTOS PODER, NIVEL, PP_MAX, PV_MAX
UPDATE_DIRVEL, //ID PERSONAGEM, DIRECAO, VELOCIDADE
ADD_QUEST, //ID QUEST, QUANTIDADE DE ITENS QUE TENHO QUE OBTER
UPDATE_QUEST, //ID QUEST, QUANTIDADE QUE CONSEGUI, QUANTIDADE DE ITENS QUE TENHO QUE OBTER
QUEST_OK, //IDQUEST, PARABENS
UPDATE_BOLSA, // ATUALIZA BOLSA DO PERSONAGEM 9 IDS
SHOW_SHOP, //ID ITENS[30], PRECO [30]
UPDATE_XP, //XP, XP_MAX
SHOT, //IDSHOT, POSICAO X E POSICAO Z INICIAL, E ID ALVO
REMOVE_PERSONAGEM, //ID PERSONAGEM
UPDATE_LEVEL,//NIVEL, QTD PONTOS DISTRIBUIR HABILIDADES PRIMARIAS, QTD PONTOS SKILL(PODER)
REMOVE_BOLSA, // ID BOLSA

//ENVIADAS
LOGIN_REQUEST, //LOGIN, SENHA
PERSONAGENS_REQUEST, //ID PESSOA
CREATE_PERSONAGEM, //ID RACA, NOME
DELETE_PERSONAGEM,
PLAY, //ID PERSONAGEM
SEND_POSITION, //ID PERSONAGEM, POSICAO X, POSICAO Z
SEND_ESTADO, //IDPERSONAGEM, ESTADO
SEND_ATACK, //ID PERSONAGEM, ID ALVO, ID ATAQUE, POSICAO X E POSICAO Z ALVO CHÃO //PODE SER PODER OU ATAQUE NORMAL
OPEN_BOLSA, //ID PERSONAGEM, ID BOLSA
CLOSE_BOLSA, //ID BOLSA
SEND_EQUIP, //ID PERSONAGEM, ID ARMA, ID ARMADURA
SEND_TARGET, //ID PERSONAGEM, ID ALVO
USE_ITEM, //IDPERSONAGEM, IDITEM
DROP_ITEM, //IDPERSONAGEM, IDITEM
SEND_MESSAGE, //ID PERSONAGEMDESTINO, MENSAGEM
SEND_ITEM,  //ID PERSONAGEM, ID ITEM, DINHEIRO
GET_ITEM_BOLSA, //ID PERSONAGEM, ID BOLSA, ID ITEM
INSERT_ITEM_BOLSA, //ID BOLSA, ID ITEM
START_SHOT, //ID PERSONAGEM, ID ALVO, IDSHOT, POSICAO X E POSICAO Z INICIAL
REQUEST_FULL_STATUS, //ID PERSONAGEM
SEND_BONUS_POINTS, //ID PERSONAGEM,VETOR EM ORDEM ALFABETICA COM QTD PONTOS DA HABILIDADE PRIMARIA USADA E A QUANTIDADE DE PONTOS DE SKILL(PODER)[PODER1,PODER2,PODER3]
ACCEPT_QUEST, // ID PERSONAGEM, ID QUEST
START_SHOP, //ID PERSONAGEM, ID NPC VENDEDOR
BUY_ITEM, //IDPERSONAGEM, IDNPC VENDEDOR, ID ITEM
REQUEST_PRICE_ITEM, //ID PERSONAGEM, ID NPCVENDEDOR, ID ITEM
SELL_ITEM, //IDPERSOANGEM, ID NPCVENDEDOR, ID ITEM, PRECO
TRADE_REQUEST, //ID PERSONAGEM, ID FREGUES
TRADE_REQUEST_ACCEPTED, //ID PERSONAGEM, ID FREGUES
TRADE_REQUEST_REFUSED, //ID PERSONAGEM, ID FREGUES
TRADE_CHANGED, //ID PERSONAGEM, ID FREGUES, idItemPersonagem, idItemFregues, qtdDinheiroPersonagem, qtdDinheiroFregues
TRADE_ACCEPTED, //ID PERSONAGEM
TRADE_REFUSED, //ID PERSONAGEM, ID FREGUES
TRADE_CONCLUDE //ID PERSONAGEM, ID FREGUES
};*/

enum TYPE_MESSAGE 
{
	DISCONNECT = 0,
	PING,
	END_FRAME,
	LOGIN_OK = 33,
	LOGIN_FAIL,
	SHOW_PERSONAGENS,
	CREATE_PLAYER_OK,
	CREATE_PLAYER_FAIL,
	DELETE_PLAYER_OK,
	DELETE_PLAYER_FAIL,
	START_GAME_FAIL,
	ENTER_CENARIO,
	ADD_PERSONAGEM,
	ADD_BOLSA,
	UPDATE_POSITION,
	UPDATE_ESTADO,
	UPDATE_ATACK,
	UPDATE_TARGET,
	OPENED_BOLSA,
	OPEN_FAIL,
	CLOSED_BOLSA,
	CLOSE_BOLSA_FAIL,
	UPDATE_EQUIP,
	SHOW_DAMAGE,
	SHOW_FULL_STATUS,
	CHAT,
	REMOVE_ITEM,
	ADD_ITEM,
	PRICE_ITEM,
	CHANGE_BUFFS,
	CHANGE_MONEY,
	CHANGE_BONUS,
	UPDATE_PVPPNIVEL,
	UPDATE_DIRVEL,
	ADD_QUEST,
	UPDATE_QUEST,
	QUEST_OK,
	UPDATE_BOLSA,
	SHOW_SHOP_PAGE,
	SHOW_ITEM_ATTRIBUTES,
	UPDATE_XP,
	SHOT,
	REMOVE_PERSONAGEM,
	UPDATE_LEVEL,
	REMOVE_BOLSA,
	ENEMY_REBORN,
	SCENE_FULL,
	NO_LOYALTY,
	DOUBLE_LOGIN,
	PORTAL_FAIL,
	INVENTORY_FULL,
	LOGIN_REQUEST,
	PERSONAGENS_REQUEST,
	CREATE_PERSONAGEM,
	DELETE_PERSONAGEM,
	START_GAME,
	SEND_POSITION,
	SEND_ESTADO,
	SEND_ATACK,
	OPEN_BOLSA,
	CLOSE_BOLSA,
	SEND_EQUIP,
	SEND_TARGET,
	USE_ITEM,
	DROP_ITEM,
	SEND_MESSAGE,
	SEND_ITEM,
	GET_ITEM_BOLSA,
	INSERT_ITEM_BOLSA,
	START_SHOT,
	REQUEST_FULL_STATUS,
	SEND_BONUS_POINTS,
	ACCEPT_QUEST,
	START_SHOP,
	REQUEST_SHOP_PAGE,
	BUY_ITEM,
	REQUEST_PRICE_ITEM,
	SELL_ITEM,
	TRADE_REQUEST,
	TRADE_REQUEST_ACCEPTED,
	TRADE_REQUEST_REFUSED,
	TRADE_CHANGED,
	TRADE_ACCEPTED,
	TRADE_REFUSED,
	TRADE_CONCLUDE,
	GET_ITEM_ATTRIBUTES,
	ENTER_PORTAL
};